// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "mstscax1.h"

/////////////////////////////////////////////////////////////////////////////
// CMstscax1

IMPLEMENT_DYNCREATE(CMstscax1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CMstscax1 properties

/////////////////////////////////////////////////////////////////////////////
// CMstscax1 operations
